### ISSUE TITLE
Keyring not found

### ISSUE THREAD

**Issue by bachoo786** [nicolas-kuechler/switchbot#11]
Hi there

I am trying to run but I get this error:

```
pi@raspberrypi:~/switchbot $ pipenv run python src/main.py
Traceback (most recent call last):
  File "src/main.py", line 1, in <module>
    from app import app
  File "/home/pi/switchbot/src/app.py", line 4, in <module>
    import keyring, logging
ModuleNotFoundError: No module named 'keyring'
```
Can you please help?

Thanks.

**Comment by nicolas-kuechler** [comment]
did you run:
`pip install pipenv`

`pipenv install`

in the root directory in the project?

Because the keyring module `keyring = "==19.1.0"` is part of the  [Pipfile](https://github.com/nicolas-kuechler/switchbot/blob/master/Pipfile).

**Comment by bachoo786** [comment]
I ran it on my desktop i.e. /home/pi

**Comment by nicolas-kuechler** [comment]
you need to run it on the raspberry pi:
i.e. `pi@raspberrypi:~/switchbot`

**Comment by bachoo786** [comment]
thanks I resolved it by running it in the switchbot directory.
