### ISSUE TITLE
Missing bot password

### ISSUE THREAD

**Issue by jxlarrea** [nicolas-kuechler/switchbot#8]
Using the REST API, all bot endpoints return 403 missing bot password. This is happening with a brand new Switchbot. I even tried to clear up the password using the app but still getting the 403 error.

Any insights? I don't see a bot password parameter in any of the the REST API endpoints.

**Comment by nicolas-kuechler** [comment]
@jxlarrea 
if you want to use a password, you need to set it with the app and then you need to perform a REST call to update the bot settings with the password.

For this perform the request:
 PATCH  `/switchbot/api/v1/bot/{bot_id}`

with the body:
`{
"password": "YOUR_PASSWORD_SET_WITHIN_THE_APP"
}
`

**Comment by jxlarrea** [comment]
Thanks for the reply @nicolas-kuechler 

Even with no password set, I am getting the 403 error previously mentioned. 

I try setting a password in the app and then tried calling the PATCH function (using the provided POSTMAN collection) but keep getting this error:

```
{
    "message": "communication with ble device failed: please retry",
    "status": "503 Service Unavailable: The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."
}
```

This is the only function giving this error, the rest all throw the 403 missing password error except for the `{{base_url}}/switchbot/api/v1/bots` endpoint with successfully returns the bot list.

**Comment by jxlarrea** [comment]
Seems like it worked setting the password even after getting the 503 error using the PATCH endpoint. Thanks for your help!

**Comment by nicolas-kuechler** [comment]
I just looked at the code and saw that I made a bot password mandatory in the REST API.
The 503 error indicates that something in the ble communication went wrong and that you need to retry. 
But I'm glad it seems to work now.

To remove the auth requirement you can search the code for `@jwt_required` annotations and remove them.
