### ISSUE TITLE
ModuleNotFoundError: No module named 'switchbot'

### ISSUE THREAD

**Issue by ronschaeffer** [nicolas-kuechler/switchbot#9]
I'm new to pipenv and probably doing something wrong. Any insight would be appreciated. I created a script sb.py containing your example code:

```
from switchbot import Scanner

scanner = Scanner()
mac_addresses = scanner.scan(known_dict={})
```
This is the result.
```
(pi) root@FICUSBOX:/home# python3 sb.py
Traceback (most recent call last):
  File "sb.py", line 1, in <module>
    from switchbot import Scanner
ModuleNotFoundError: No module named 'switchbot'
```
Should the environment include a module named "switchbot"?
Any tips?

Thank you very much.

**Comment by nicolas-kuechler** [comment]
@ronschaeffer 
No, the environment does not include a switchbot module, it only includes all the other dependencies.

Your script sb.py has to be in the same folder as the scripts switchbot.py, switchbot_timer.py, and switchbot_util.py from the repository.

**Comment by emkayg** [comment]
Unfortunately as python newbie, I'm not understanding how to use this or even where those other scripts come from. Hoping someone can help.
